service: my-typescript-lambda

provider:
  name: aws
  runtime: nodejs20.x 
  region: us-east-1 
  architecture: arm64

functions:
  hello:
    handler: dist/handlers/place-auction-bid.handler
    events:
      - httpApi:
          path: /hello
          method: get
